# Copyright (C) 2018 by Thomas A. Early, N7TAE

# if you make changed in these two variable, you'll need to change things
# in the main.h file as well as the systemd service file.
BINDIR=/usr/local/bin
CFGDIR=/usr/local/etc

EXECUTABLE=xlxd
GCC=g++
CFLAGS=-c -W -Wall -MMD -MD -std=c++11
# uncomment the next line for an executable with full gdb debugging support
#CFLAGS=-c -ggdb3 -W -Wall -MMD -MD -std=c++11
LDFLAGS=-pthread
SOURCES=$(wildcard *.cpp)
OBJECTS=$(SOURCES:.cpp=.o)
DEPENDS=$(SOURCES:.cpp=.d)

all : $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE) : $(OBJECTS)
	$(GCC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o :
	$(GCC) $(CFLAGS) $< -o $@

clean :
	$(RM) $(EXECUTABLE) *.o *.d

-include $(DEPENDS)

# install and uninstall need root level permission
install :
	ln -s $(shell pwd)/$(EXECUTABLE).blacklist $(CFGDIR)/$(EXECUTABLE).blacklist
	ln -s $(shell pwd)/$(EXECUTABLE).whitelist $(CFGDIR)/$(EXECUTABLE).whitelist
	ln -s $(shell pwd)/$(EXECUTABLE).linklist $(CFGDIR)/$(EXECUTABLE).linklist
	cp -f ../systemd/$(EXECUTABLE).service /lib/systemd/system/
	cp -f $(EXECUTABLE) $(BINDIR)
	systemctl enable $(EXECUTABLE).service
	systemctl daemon-reload
	systemctl start xlxd

uninstall :
	rm -f $(CFGDIR)/$(EXECUTABLE).blacklist
	rm -f $(CFGDIR)/$(EXECUTABLE).whitelist
	rm -f $(CFGDIR)/$(EXECUTABLE).linklist
	systemctl stop $(EXECUTABLE).service
	systemctl disable $(EXECUTABLE).service
	systemctl daemon-reload
